# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  # aliased to 5.3.29
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  - DB=pgsql

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm

install:
  - sudo apt-get install -y zip

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-clover=coverage.xml

# configure notifications (email, IRC, campfire etc)
notifications:
  irc: "irc.freenode.org#yourfavouriteroomfortravis"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - zip portfolio-${TRAVIS_TAG}.zip HelloWorld.php

deploy:
  provider: releases
  api_key:
    secure: bqf0gOzKw18If5g6f5+68Eg+MUAa9KyYiYdOYbAUtZUTuCCZfEexU1njA75xCoPN+IO0oVJ8EXSZM9fCnsnqCBPc2P7RCqUKAUjbIrvizfgRpKilftFVqfV2yIJ1qSsGKhAMWVIgmCgbaG2hW0d+BBEDloNQhIMJHkdZUiI1E9rJR9mxgnhKZrls5axOyebRUm/r34MbnYiyywVjiSyACE+nSplsJNyBqP8yMiD/OlL7H2nSytcvEpRSHQfagp0p9r6YRB2e17t6+ITX71pKFttXdjlCbfomo0QhwgwdllokkQxaq5gGv8nSujpn1GPuNuWP+h/ifRrFgq7PzwsfgCtLjY5weTF9/EzRRwuOqH+Fb57I+Azd73PFH6IYpBP8QQFzCV7Tty9br4B5SBuwkOOdIw0IZOYaOYuH5n+GJIeziSHWT5K6l1qXYBKdP0N1dgpKtUPxY/1prvw8OVdEGsR6uf+pnAnINJ34N24iEC/krnsQ1V3bZrHNxTsxxt9B4wQY0N+pAb1TvxQlJnutY0zFbD3T3pD4WsxEfN1G8uLV4a6pW9TExI9GpCXIJV4MqP0k8iuOTHu2N0WeGHKtqunLZCv8dFEZmpawiMy5b4ppNVaHbfpQCsbSkRjkgN2k87Z4Oih7SjXx5ySQdYplKJY9OoZw0vPLT2ga8ZXlhk4=
  file: php-${TRAVIS_TAG}.zip
  on:
    tags: true
skip_cleanup: true
