language: php
php:
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
env:
  matrix:
  - DB=mysql
  - DB=pgsql
matrix:
  exclude:
  - php: hhvm
    env: DB=pgsql
  allow_failures:
  - php: 7.0
  - php: hhvm
install:
- sudo apt-get install -y zip
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;"
  -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres;
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;"
  -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-clover=coverage.xml
notifications:
  irc: irc.freenode.org#yourfavouriteroomfortravis
after_success:
- bash <(curl -s https://codecov.io/bash)
- zip portfolio-${TRAVIS_TAG}.zip HelloWorld.php

before_deploy:
- git config --global user.email "github@travis-ci.org"
- git config --global user.name "Travis CI"

deploy:
  provider: releases
  file: php-${TRAVIS_TAG}.zip
  api_key:
    secure: X1MfM2ZmrGLXFCVt5tcRWFxuEplypMxu2kRqEn4lVAOhsKllpGths3A3sMj4JmRIedF94IWasZzJ69guAlUU0yrXN/7S6xA0s1QXQkK/K7IgZ3c5hoLKVfz3GRPWK5O+SBWmts8x9BN0XNXGF8hu2Ta/kOrA4Aynf8J538RxG0Ocj8byzNNlDjHp4UP/cR7ZMVuf0UnucusvBXU5JaswxHD1CKjcDTc70wMAx2ZyGjshE/OX6uLVlF0ljhYswSKsvkMHBZdOKUIQdrf2pko8xNlbH+6NSrcKuIedSmvjtP49H7Wwx90rECMHHjdNLIVblnKwbf8hknnHO8Vu5NM+x+4dRlRtJZYlf1j5hVm1dCr5WxWOZC9Q2H8Njn8+oNXdbpS9kQs26IEtcA48sO3NzCwVhExbQQz8OHaYHiYi+vs3wt8XJhIlvnORq9YjUjhFyOU80Au077bqPTGHHzXgmEVZZ7Y63idxpxlQhHSJRNeIJiMTIDvEUphhOlSWzVB40zW6WaJS6lx80N+LJV+9rYVZICWY73Jza3sXCv/r17hgW9HDIjajoRZmeWOTzJY1ACeiRF9G2zzQIG+WLUKoTa/h+mQSM/E8uridc4Vtw/zvDfJdbV4mP3gpA/FeXVqgC+WTdb5rcViQ1mLbz73smttqgqegYitDYqxUDxRq/AQ=
  on:
    tags: true
skip_cleanup: true
