language: php
php:
- 5.2
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- hhvm
env:
  matrix:
  - DB=mysql
  - DB=pgsql
  global:
  - secure: h2TnVfu/omv2XuZLcLGjHs+hLlt9K4mcUp8k7sMumOZqFxOW3qCJ1YeiLSubqzCin2FYdaFUnosGN7noBdPUD7SpQ1IdLiTG0wrRzN/6j48daSb+Hyf8433/ssb7v2/J9hfnGsjph8NFkhE6/Ea8qfJ/Ngf7Wu+KxQAasdF5SqE7F2hc2vsRUYXPAxxmRaJBaVXQ8Mfviv8brF9mfjCT28uIKs/i/RFaH3OKOf+oV1wAI//u8TIkpM88dOQmgj1ibzqZ5gGBzLqyyMNAmkJWFbBzyrm/tAo0zWDet/xQb/EXKpWQnKxlZ/n4PJZc0mLqGRmWU7GPQBTBYLt2DKpF3Qzpx0nCg9hWvwoACjCqTs3W+SIqEedlhNOo17AiWpQ41PZ/81UlX/9ZjwsOn+OpFjkmoPL6FEPLnjINq2qZKX3/ge3SwTi1dL8Ze0SX/xvjKeXVKVbYHiGqSxuQzJqMPX9Gf2aDdmyD7Ik+i9zRyo/YputZ3nQn+D8liu4cb2/4fJuL8q+ihAH8ulkUdg+leVS4S6SK2R/Zx+QwV2M3IflF13mleIy1TAF+HOg6DQ1TRpSmqUSvEvz7GEtPJAarU5tNP0KNawXTM52BtTxcmvqKBgEsoQstWb9uxgKlNLxHpzn0NOIK10mOk8tTj0qjyGzrJJWtMllpl9UuVbrr6fg=
  - secure: Lenv0n3aLRCBdBO1ptQmo2WDlDdQfwjN/b4TyF8OyKxFkTptP3Ndx+DIEuy75mSM3eIX2M57S3UCE4595+j/UDhE1eng1L6awQBQH6RVigDNzFOm0kyIlgq/URTvMJO7mZjhRJWYJsxGAuEE7s/Brgmtmi6Gi7YoJ53FZfou7c4rf5ppcBI3HR9ar1tZpi9qF02ffAElc6Ps/2qznmlYTeIofTZpfAp7Bx3pZPC+sqp89jXHDteiaehbvSzNi24Xp8KclJp0YxcNNPkwvs9yqEISKAJ9yazE6WjkjU29FXdURsjZrZ/htdTbkZ69WlMbnaC5+MPLtDKmDqtzXkKg9mT9xyMW3Y3qmFgWB7BTxG4bGMwwdto0r3B96fRJGi2I27Hgwd5I9qStypNtHUACiK2nJ112lcM3QOMgJycywm2cM2XxhgreMC7uoW/XKxkNjFlyltclQC38gYjK4QTpvw8I1etn0R59FhdN6fE5BxKDIqRDOPV0fBmxA1zJI6WeX+huhhhGFCy2O9fM2ht97iHjyz5GtJoXD8JbynwGB57T5rfzu4cIM7pW708+1EIhKOwoTPA2vDpJTWfXwo8i2+xBtrU69GX0bi7FybKR8f4FesB9yyUrxiX9QmapNzGMz8e8KZqAMtJpX1BhG/aPkLgOgK2L957I4BQ1LGfBziI=
  - secure: M4HjzsL3iOsShtZyhNeWacYw9mBEUYXq0aXD6sRfw7NQd7dm/zpOdZSevgl0a+QCxmEzV/FN64TIrirkDhdsNEgXpdDHe1YX6+yEP+MJSggkCXNsavtIGixoAVOXc5aXo7MofUF8tNxG0uvTJEKGvA+6bzr/6QaLVam3tHfDwa7wUKn/ke7LtAFs5eGY4/+Gsi25InoOnu5Hb1gesINdfNlDh+TnvM2M+DVQ6S5XsLZSYV2D0c2VZ4l+NJpWdHhdzqcLBCfs/erzpjlJtpqlLCEGJYI3czhpD3RwW4jG7ghZmpKKlB1tU413FxpSAh8g8EP9RFgKzF2MUyx1ZVJExxiUP0rqIny+x8NCGPflNZ8Mv6ZWQm+fveleJNXPlJFrclFxej2H3AMBuqVvKnESYN1KP63rWufb2lOQW9zHi5q/bFXCRmwwX4WloSsh81Mc9mH9Ye/hYS5SR8F8zMn94NbNIHX9sUBALuuJeiEiXGj9zdUxG0aVZaNcQaxRYn8klFbm4WuPo0DWyJ6rMT64NJJIPWU5+L2tagIA0DIMq9AgrotUtaD08SU7FXrPN8bEFWpfiC9xECCJtEimX/DaLIgf6koLJ+ca8zMTrxIV3hz+2xWXC2k8X3WdhTzZv36akvJrP/Uw9Hb4ljL0IVTNyms7AliQNuDRET3oBRXM40A=
  - secure: ppoMNVcq6OXprRltKDlyM7ZxJ2a8zO9j++6mNV5JbNMZEpEFwV6YgkZaCguskT6t0NfMo5k8/b1s0Gm7lEx9kLjsTtuGlSwns1KAaiNlSiiuvIewgrGseyybuw8qQFL4F7roHG+H4a1WCAj9Fcbqqgr+VXLqjo/bA6KHS/jOJBY5SQlzO4Nk6eBAF8LBIIcIT3Bi514hiC9Eb9oih8DM1yPewxnpwVAR9UXGbNiso0IVUYHMu3aKx3m34ooZTf/qmw2xLxJoOGC4ODeaCyrRv2uaCvDYJOcUFq4U9YD8sLBXRzu8ra8XhUTk8TlOY1cS7KzN8DEPAidt8S3vGQYPiTMOXOv3FM4g/qCJyS77jv1ZTXu0FlKoJjLFq1I6D8E+gJ0pQmk8JBmvnzT2KIaHOk0evF2QE7fixXdWZM9IqF/SoV7pMbeiGbg98Ly9NIigCeka64yeDQKOaBG3JARZubxe7yPXy9ZVKjk9K2s9IraGqc7MyGcTDcKJq+w6vkDkXMgx/A1mgRTZCI+j4BHeTh8lSIax14QiOFovX98hUAxX7hafGHIK39kvyhONVsTcGocDpofI3U3YduRTnCXGUZniXYyB/Z9Mx8z4rjhjXD1cs1dTJOeZiTzPsSLQySnNyrqOalBzknub6SfImfqG6mNSixJ4Z51llddFwuSggj4=
matrix:
  exclude:
  - php: hhvm
    env: DB=pgsql
  allow_failures:
  - php: 7.0
  - php: hhvm
install:
- sudo apt-get install -y zip
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;"
  -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres;
  fi
- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;"
  -uroot; fi
script: phpunit --configuration phpunit_$DB.xml --coverage-clover=coverage.xml
notifications:
  irc: irc.freenode.org#yourfavouriteroomfortravis
after_success:
- bash <(curl -s https://codecov.io/bash)
- zip portfolio-${TRAVIS_TAG}.zip HelloWorld.php
deploy:
  provider: releases
  file: php-${TRAVIS_TAG}.zip
  on:
    tags: true
skip_cleanup: true
